apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradein-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: backend-container
        image: rohit0301/backend:v2
        ports:
        - containerPort: 8000  

---
apiVersion: v1
kind: Service
metadata:
  name: tradein-backend-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000

