apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradein-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: tradein-frontend-container
        image: rohit0301/frontend-nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tradein-frontend-service
spec:
  selector:
    app: react
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000 
  type: NodePort

